[package]
name = "game4D"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
glam = "0.21.2"
rand = { version = "0.8.5", features = [ "small_rng" ] }
std140 = "*"